# see https://eslint.org/docs/user-guide/configuring/

env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  # tsconfigRootDir: __dirname
  project: ./tsconfig.eslint.json
settings:
  react:
    version: detect
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
root: true
rules:
  react/display-name: off
  react/prop-types: off
  react/react-in-jsx-scope: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
overrides:
  - files: '*.js'
    rules:
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/explicit-function-return-type': off
